In [2]:
# NumPy - linear algebra library for Python 

In [3]:
list_e = [1, 2, 3]

In [4]:
list_e

In [ ]:
import numpy as np

In [ ]:
arr = np.array(list_e)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
mx = np.array([[1,2,3], [2,1,3], [3,2,1]])

In [ ]:
mx

array([[1, 2, 3],
       [2, 1, 3],
       [3, 2, 1]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5, 2))

In [ ]:
np.ones((1,2))

In [ ]:
np.linspace(0, 5, 100)

In [ ]:
np.eye(10)

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(5, 5)

In [ ]:
np.random.randn(10, 3)

In [ ]:
np.random.randint(1, 100, 10)

In [ ]:
rarr = np.random.randint(1, 100, 10)

In [ ]:
rarr

In [ ]:
rarr.reshape(5,2)

In [ ]:
rarr.max()

In [ ]:
rarr[0].max()

In [ ]:
rarr.argmax()

In [ ]:
rarr.shape

In [ ]:
rarr

In [ ]:
rarr.dtype

In [ ]:
arr = np.arange(0, 11)

In [ ]:
arr

In [ ]:
arr[3]

In [ ]:
arr[:5]

In [ ]:
arr[1:]

In [ ]:
arr = 100

In [ ]:
arr

In [ ]:
arr = np.arange(0, 11)

In [ ]:
arr[:] = 100

In [ ]:
arr

In [ ]:
arr = np.arange(0, 11)

In [ ]:
arr

In [ ]:
x = arr

In [ ]:
x

In [ ]:
arr

In [ ]:
x[:2] = 100

In [ ]:
x

In [ ]:
arr

In [ ]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [ ]:
arr2d

In [ ]:
arr2d[0, 0]

In [ ]:
arr2d[2]

In [ ]:
arr2d[0][0]

In [ ]:
arr2d[0, 0] = 100

In [12]:
arr2d

NameError: name 'arr2d' is not defined

In [ ]:
arr2d[:,:]

In [ ]:
arr2d[:2,:2]

In [ ]:
arr2d[:2,1:]

In [ ]:
arr2d[1:,1:]

In [ ]:
arr2d[True]

In [ ]:
arr2d[arr2d > 10]

In [ ]:
arr2d = np.arange(50).reshape(5, 10)

In [ ]:
arr2d

In [ ]:
arr2d[1:3,3:5]

In [ ]:
arr = np.arange(0, 11)

In [ ]:
arr

In [ ]:
arr + arr

In [ ]:
# scalar - single number

In [ ]:
arr + 2

In [ ]:
arr * 3

In [ ]:
arr

In [ ]:
arr ** 3

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.tan(arr)