In [1]:
# NumPy - linear algebra library for Python 

In [2]:
list_e = [1, 2, 3]

In [3]:
list_e

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
arr = np.array(list_e)

In [6]:
arr

array([1, 2, 3])

In [7]:
mx = np.array([[1,2,3], [2,1,3], [3,2,1]])

In [8]:
mx

array([[1, 2, 3],
       [2, 1, 3],
       [3, 2, 1]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones((1,2))

array([[1., 1.]])

In [13]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.35535665, 0.37293952, 0.80608985, 0.74950946, 0.64703223])

In [16]:
np.random.rand(5, 5)

array([[0.74238533, 0.83011889, 0.22029212, 0.83183845, 0.74161457],
       [0.9588174 , 0.82464524, 0.37779083, 0.97272251, 0.53048566],
       [0.04589236, 0.2954985 , 0.03805578, 0.53452859, 0.73318033],
       [0.11278748, 0.80614514, 0.82544127, 0.09563553, 0.12013102],
       [0.38090265, 0.93509539, 0.16795145, 0.35065582, 0.60395175]])

In [17]:
np.random.randn(10, 3)

array([[-1.28255594,  1.42821133, -0.64880521],
       [ 1.17007595,  0.5572192 , -0.11332321],
       [-1.85121864,  0.75995728, -0.65872748],
       [-0.50673561,  0.41522645,  1.11797022],
       [ 1.5637539 ,  0.63891181, -0.30590681],
       [-1.66706101,  1.65105235,  0.44406464],
       [ 0.43093295, -1.76547525, -0.07350606],
       [ 0.05204305, -1.64282096, -1.70050938],
       [ 0.52582313,  0.11973905,  0.21302755],
       [-0.0528956 , -0.35185286,  0.39860708]])

In [18]:
np.random.randint(1, 100, 10)

array([72, 36, 65, 21, 99, 48, 84, 39, 48, 60])

In [19]:
rarr = np.random.randint(1, 100, 10)

In [20]:
rarr

array([36, 96, 46, 63, 87, 64, 33, 77, 44, 72])

In [21]:
rarr.reshape(5,2)

array([[36, 96],
       [46, 63],
       [87, 64],
       [33, 77],
       [44, 72]])

In [22]:
rarr.max()

96

In [23]:
rarr[0].max()

36

In [24]:
rarr.argmax()

1

In [25]:
rarr.shape

(10,)

In [26]:
rarr

array([36, 96, 46, 63, 87, 64, 33, 77, 44, 72])

In [27]:
rarr.dtype

dtype('int64')

In [28]:
arr = np.arange(0, 11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[3]

3

In [31]:
arr[:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr = 100

In [34]:
arr

100

In [35]:
arr = np.arange(0, 11)

In [36]:
arr[:] = 100

In [37]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr = np.arange(0, 11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
x = arr

In [41]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
x[:2] = 100

In [44]:
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [45]:
arr

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [46]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [47]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr2d[0, 0]

5

In [49]:
arr2d[2]

array([35, 40, 45])

In [50]:
arr2d[0][0]

5

In [51]:
arr2d[0, 0] = 100

In [52]:
arr2d

array([[100,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [53]:
arr2d[:,:]

array([[100,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [54]:
arr2d[:2,:2]

array([[100,  10],
       [ 20,  25]])

In [55]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [56]:
arr2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [57]:
arr2d[True]

array([[[100,  10,  15],
        [ 20,  25,  30],
        [ 35,  40,  45]]])

In [58]:
arr2d[arr2d > 10]

array([100,  15,  20,  25,  30,  35,  40,  45])

In [59]:
arr2d = np.arange(50).reshape(5, 10)

In [60]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [62]:
arr = np.arange(0, 11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
# scalar - single number

In [66]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [71]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [72]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [73]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])